# -*- coding: utf-8 -*-
# © 2018 Comunitea
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
from . import building_site_services
from . import service_picking_valorization_rel
from . import service_picking_other_concepts_rel
from . import stock_service_picking
from . import account_invoice
from . import stock_service_picking_line
from . import service_picking_invoice_concept
from . import product
from . import partner
from . import account_analytic_account
from . import waste_services
from . import stock_picking
from . import fleet
from . import valorization_lines
from . import res_company
from . import stock_move
from . import timesheet
from . import other_expenses
from . import account_analytic_distribution
from . import stock_service_picking_ddd
from . import types_ddd
from . import detected_species
from . import products_used
from . import legionella_samples
from . import type_of_installation_legionella
from . import machinery_to_employ
from . import equipment_to_be_used
from . import observation_recommendation_ddd
